# Generated by Django 3.2.8 on 2022-04-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20220419_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
    ]
