# Generated by Django 3.2.8 on 2022-04-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20220419_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='animales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('edad', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('genero', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='Correo')),
            ],
        ),
        migrations.DeleteModel(
            name='contacto',
        ),
    ]
