# Generated by Django 3.2.8 on 2022-04-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_auto_20220426_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animales',
            new_name='animal',
        ),
    ]
