# Generated by Django 3.2.8 on 2022-04-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_vacuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='vacuna_animal',
        ),
        migrations.DeleteModel(
            name='animal',
        ),
    ]
