# Generated by Django 3.2.8 on 2022-04-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_auto_20220426_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('edad', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('genero', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='Correo')),
                ('vacuna_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.vacuna')),
            ],
        ),
    ]
