# Generated by Django 3.2.8 on 2022-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='nombre',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='vacuna',
            field=models.CharField(max_length=100, null=True, verbose_name='vacuna'),
        ),
    ]
